"""empty message

Revision ID: 846f7e8f1cd5
Revises: 
Create Date: 2025-08-01 14:17:27.768812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846f7e8f1cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=150), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('project_image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_title', sa.String(length=150), nullable=False),
    sa.Column('skill_image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', 'skill_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('projects')
    # ### end Alembic commands ###
